export const TEXT_TRANSLATE = {
  MESSAGE_ERROR: {
    SUB_CATEGORY_NOT_EXISTS: "Danh mục phụ không tồn tại",
    SUB_CATEGORY_ALREADY_EXISTS: "Danh mục phụ đã tồn tại",
  },
  MESSAGE_SUCCESS: {
    CREATE_SUCCESSFUL: "Tạo danh mục phụ thành công",
    UPDATE_SUCCESSFUL: "Cập nhật danh mục phụ thành công",
    DELETE_SUCCESSFUL: "Xóa danh mục phụ thành công",
  },
  MESSAGE_VALIDATE: {
    NAME_REQUIRED: "Vui lòng nhập tên danh mục phụ",
    DESCRIPTION_REQUIRED: "Vui lòng nhập mô tả",
  },
  TITLE: {
    CODE: "Mã danh mục",
    ICON: "Ký hiệu",
    MANAGE_SUB_CATEGORY: "Quản lý danh mục phụ chi tiêu",
    SUB_CATEGORY_LIST: "Danh sách danh mục phụ chi tiêu",
    INDEX: "STT",
    NAME: "Tên danh mục phụ",
    DESCRIPTION: "Mô tả",
    TYPE: "Loại",
    STATUS: "Trạng thái",
    ACTIVE: "Hoạt động",
    INACTIVE: "Không hoạt động",
    FUNCTIONS: "Chức năng",
    CREATED_AT: "Ngày tạo",
    TITLE: "Xác nhận",
    CONTENT: "Bạn có chắc chắn muốn xóa danh mục phụ này?",
    OK_TEXT: "Đồng ý",
    CANCEL_TEXT: "Hủy",
    SEARCH: "Tìm kiếm danh mục",
    MAIN_CATEGORY_TAB: "Danh mục chính",
    SUB_CATEGORY_TAB: "Danh mục phụ",

    MAIN_CATEGORY: "Danh mục chính",
    SEARCH_SUB: "Tìm kiếm danh mục phụ",
    CATEGORY_DETAIL: "Chi tiết danh mục phụ",
    NAME_UNSIGN: "Tên không dấu",
    UPDATED_AT: "Ngày cập nhật",
    UPDATED_BY: "Người cập nhật",
    CREATED_BY: "Người tạo",
    MAIN_CATEGORY_INFO: "Thông tin danh mục chính",
    SUBCATEGORIES: "Danh sách danh mục phụ",
  },
  BUTTON: {
    ADD_CATEGORY: "Thêm danh mục",
    SAVE: "Lưu",
    CANCEL: "Hủy",
    ADD_SUB_CATEGORY: "Thêm danh mục phụ",
  },
};
