export const TEXT_TRANSLATE = {
  TITLE: {
    INDEX: "STT",
    EMAIL: "Email",
    FULLNAME: "Họ và tên",
    DOB: "Ngày sinh",
    ADDRESS: "Địa chỉ",
    PHONE_NUMBER: "Số điện thoại",
    ROLE: "Vai trò",
    STATUS: "Trạng thái",
    FUNCTIONS: "Chức năng",
    USER: "Người dùng",
    ADMIN: "Quản lý",
    ACTIVE: "HOẠT ĐỘNG",
    INACTIVE: "KHÔNG HOẠT ĐỘNG",
    BAN_USER: "Bạn có muốn cấm người dùng này không?",
    YES: "Có",
    NO: "Không",
    USER_LIST: "Danh sách người dùng",
    SEARCH: "Tìm kiếm...",
    AVATAR: "Ảnh đại diện",
    ADD_USER: "Thêm người dùng",
    CHOOSE_ROLE: "Chọn vai trò",
    MANAGE_USER: "Quản lý người dùng",
  },
  BUTTON: {
    ADD_USER: "Thêm người dùng",
    ADD_AVATAR: "Thêm ảnh",
    CONFIRM: "Xác nhận",
    CANCEL: "Hủy bỏ",
  },

  MESSAGE_VALIDATE: {
    EMAIL_REQUIRED: "Vui lòng nhập email",
    NAME_REQUIRED: "Vui lòng nhập họ và tên",
    PASSWORD_REQUIRED: "Vui lòng nhập mật khẩu",
    CONFIRM_PASSWORD_REQUIRED: "Vui lòng xác nhận lại mật khẩu",
    PHONE_NUMBER_REQUIRED: "Vui lòng nhập số điện thoại",
    DOB_REQUIRED: "Vui lòng chọn ngày tháng năm sinh",
    ROLE_REQUIRED: "Vui lòng chọn vai trò",

    INPUT_PHONE_NUMBER: "Vui lòng nhập đúng số điện thoại (10 chữ số)",
    INPUT_EMAIL: "Email phải đúng định dạng",
    PASSWORD_8_CHARACTERS: "Mật khẩu phải có ít nhất 8 ký tự",
    PASSWORD_MIN_LENGTH: "Mật khẩu phải có ít nhất 8 ký tự",
    PASSWORDS_MUST_MATCH: "Mật khẩu và xác nhận mật khẩu phải giống nhau",
    OTP_5_DIGITS: "Vui lòng nhập đầy đủ 5 số",
    RECAPTCHA_REQUIRED: "Vui lòng xác nhận reCAPTCHA",
  },

  MESSAGE_ERROR: {
    INVALID_INFO: "Tài khoản hoặc mật khẩu không chính xác",
    ACCOUNT_ALREADY_EXISTED: "Tài khoản đã tồn tại",
    PHONE_ALREADY_EXISTED: "Số điện thoại đã tồn tại",
    VERIFIED_EMAIL: "Tài khoản này đã tồn tại",
    OTP_INVALID: "Mã OTP đã hết hạn hoặc không hợp lệ",
    ACCOUNT_DOES_NOT_EXIST: "Tài khoản không tồn tại",
    MUST_BE_16: "Người dùng phải từ 16 tuổi trở lên mới dược vào hệ thống",
  },

  MESSAGE_SUCCESS: {
    CREATE_SUCCESSFUL: "Tạo người dùng thành công",
  },
};
