import { LoadingWrapper, NextProgressBar, ProgressBar } from "@/components";
import { Providers } from "@/redux/provider";
import { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import useUserInfo from "@/hooks/useUserInfo";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-robotoSlab",
});

export const metadata: Metadata = {
  title: "MoneyEz | Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={`${robotoSlab.variable}`}>
        <Providers>
          <LoadingWrapper>
            <NextProgressBar />
            {children}
            <ProgressBar />
            <Toaster position="top-right" richColors />
          </LoadingWrapper>
        </Providers>
      </body>
    </html>
  );
}
