export const TEXT_TRANSLATE = {
  TITLE: {
    SUB_TITLE: "Góp quỹ thông minh – Dự án chung tay phát triển bền vững",
    INDEX: "STT",
    NAME: "Tên nhóm",
    DESCRIPTION: "Mô tả",
    AVATAR: "Ảnh nhóm",
    MEMBER_COUNT: "Số thành viên",
    STATUS: "Trạng thái",
    FUNCTIONS: "Chức năng",
    ACTIVE: "HOẠT ĐỘNG",
    INACTIVE: "KHÔNG HOẠT ĐỘNG",
    GROUP_LIST: "Danh sách nhóm",
    SEARCH: "Tìm kiếm...",
    ADD_GROUP: "Thêm nhóm",
    MANAGE_GROUP: "Quản lý nhóm",
    TITLE: "Xóa nhóm",
    CONTENT:
      "Bạn có muốn xóa nhóm này không? Nhóm này không thể được khôi phục.",
    OK_TEXT: "Có",
    OK_TYPE: "danger",
    CANCEL_TEXT: "Không",
    BALANCE: "Số dư",
    VISIBILITY: "Quyền riêng tư",
    PUBLIC: "CÔNG KHAI",
    PRIVATE: "RIÊNG TƯ",
    CREATED_DATE_GROUP: "Ngày tạo nhóm:",
    UPDATED_DATE_GROUP: "Cập nhật lần cuối:",
    CURRENT_BALANCE: "Số dư hiện tại",
    TEAM_MEMBERS: "Thành viên nhóm",
    MEMBER: "Thành viên",
    ROLE: "Vai trò",
    CONTRIBUTION: "Đóng góp",
    GROUP_MEMBER_STATUS: "Trạng thái",
    PARTICIPATE_DATE: "Ngày tham gia",
    INFO_DETAIL_MEMBER: "Chi tiết thành viên",
    PHONE_NUMBER: "Số điện thoại:",
    DOB: "Ngày sinh:",
    GENDER: "Giới tính:",
    ADDRESS: "Địa chỉ:",
    CONTRIBUTION_MEMBER: "Đóng góp:",
    PARTICIPATE_DATE_MEMBER: "Ngày tham gia:",
  },

  BUTTON: {
    ADD_GROUP: "Thêm nhóm",
    ADD_AVATAR: "Thêm ảnh",
    CONFIRM: "Xác nhận",
    CANCEL: "Hủy bỏ",
  },

  MESSAGE_VALIDATE: {
    NAME_REQUIRED: "Vui lòng nhập tên nhóm",
  },

  MESSAGE_ERROR: {
    GROUP_ALREADY_EXISTS: "Nhóm đã tồn tại",
    GROUP_NOT_EXISTS: "Nhóm không tồn tại",
  },

  MESSAGE_SUCCESS: {
    CREATE_SUCCESSFUL: "Tạo nhóm thành công",
    DELETE_SUCCESSFUL: "Xóa nhóm thành công",
  },
};
