export const TEXT_TRANSLATE = {
  MESSAGE_ERROR: {
    CATEGORY_NOT_EXISTS: "Danh mục không tồn tại",
    CATEGORY_ALREADY_EXISTS: "Danh mục đã tồn tại",
  },
  MESSAGE_SUCCESS: {
    CREATE_SUCCESSFUL: "Tạo danh mục thành công",
    UPDATE_SUCCESSFUL: "Cập nhật danh mục thành công",
    DELETE_SUCCESSFUL: "Xóa danh mục thành công",
    ASSIGN_SUBCATE_SUCCESSFUL: "Gán danh mục con thành công",
    REMOVE_SUBCATE_SUCCESSFUL: "Xóa danh mục con thành công",
  },
  MESSAGE_VALIDATE: {
    NAME_REQUIRED: "Vui lòng nhập tên danh mục",
    DESCRIPTION_REQUIRED: "Vui lòng nhập mô tả",
  },
  TITLE: {
    SUB_TITLE_DETAIL:
      "Phân tích chi tiết các mục trong danh mục để đưa ra quyết định chính xác",
    SUB_TITLE: "Dễ dàng kiểm soát ngân sách với danh mục chi tiêu hợp lý",
    CODE: "Mã danh mục",
    ICON: "Ký hiệu",
    MANAGE_CATEGORY: "Quản lý danh mục chi tiêu",
    CATEGORY_LIST: "Danh sách danh mục chi tiêu",
    INDEX: "STT",
    NAME: "Tên danh mục",
    DESCRIPTION: "Mô tả",
    TYPE: "Loại",
    STATUS: "Trạng thái",
    ACTIVE: "Hoạt động",
    INACTIVE: "Không hoạt động",
    FUNCTIONS: "Chức năng",
    CREATED_AT: "Ngày tạo",
    TITLE: "Xác nhận",
    CONTENT: "Bạn có chắc chắn muốn xóa danh mục này?",
    OK_TEXT: "Đồng ý",
    CANCEL_TEXT: "Hủy",
    SEARCH: "Tìm kiếm danh mục",
    MAIN_CATEGORY_TAB: "Danh mục chính",
    SUB_CATEGORY_TAB: "Danh mục con",
    MANAGE_SUB_CATEGORY: "Quản lý danh mục con",
    SUB_CATEGORY_LIST: "Danh sách danh mục con",
    MAIN_CATEGORY: "Danh mục chính",
    SEARCH_SUB: "Tìm kiếm danh mục con",
    CATEGORY_DETAIL: "Chi tiết danh mục",
    NAME_UNSIGN: "Tên không dấu",
    UPDATED_AT: "Ngày cập nhật",
    UPDATED_BY: "Người cập nhật",
    CREATED_BY: "Người tạo",
    MAIN_CATEGORY_INFO: "Thông tin danh mục chính",
    SUBCATEGORIES: "Danh sách danh mục con",
    SELECT_SUBCATEGORIES: "Chọn danh mục con",
    ADD_SUB_CATEGORY_TO_CATEGORY: "Thêm danh mục con vào danh mục",
    ACTION: "Thao tác",
    REMOVE_SUBCATEGORY: "Xóa danh mục con",
    REMOVE_SUBCATEGORY_CONFIRM:
      "Bạn có chắc chắn muốn xóa danh mục con này khỏi danh mục chính?",
    ADD_CATEGORY: "Thêm danh mục",
    UPDATE_CATEGORY: "Cập nhật danh mục",
  },
  BUTTON: {
    ADD_CATEGORY: "Thêm danh mục",
    UPDATE_CATEGORY: "Cập nhật danh mục",
    SAVE: "Lưu",
    CANCEL: "Hủy",
    ADD_SUB_CATEGORY: "Thêm danh mục con",
    REMOVE: "Xóa",
  },
};
