export const TEXT_TRANSLATE = {
  MESSAGE_ERROR: {
    POST_NOT_EXISTS: "bài viết phụ không tồn tại",
    POST_ALREADY_EXISTS: "bài viết phụ đã tồn tại",
  },
  MESSAGE_SUCCESS: {
    CREATE_SUCCESSFUL: "Tạo bài viết phụ thành công",
    UPDATE_SUCCESSFUL: "Cập nhật bài viết phụ thành công",
    DELETE_SUCCESSFUL: "Xóa bài viết phụ thành công",
  },
  MESSAGE_VALIDATE: {
    NAME_REQUIRED: "Vui lòng nhập tên bài viết",
    DESCRIPTION_REQUIRED: "Vui lòng nhập mô tả",
  },
  TITLE: {
    CODE: "Tiêu đề",
    SHORT_CONTENT: "Tóm tắt nội dung",
    CONTENT: "Nội dung",
    THUMBNAIL: "Ảnh bìa",
    ICON: "Ký hiệu",
    MANAGE_POST: "Quản lý bài viết",
    POST_LIST: "Danh sách bài viết",
    INDEX: "STT",
    NAME: "Tên bài viết",
    DESCRIPTION: "Mô tả",
    TYPE: "Loại",
    STATUS: "Trạng thái",
    ACTIVE: "Hoạt động",
    INACTIVE: "Không hoạt động",
    FUNCTIONS: "Chức năng",
    CREATED_AT: "Ngày tạo",
    TITLE: "Xác nhận",
    CONTENT_CONFIRM: "Bạn có chắc chắn muốn xóa bài viết này?",
    OK_TEXT: "Đồng ý",
    CANCEL_TEXT: "Hủy",
    SEARCH: "Tìm kiếm bài viết",
    MAIN_CATEGORY_TAB: "bài viết chính",
    POST_TAB: "bài viết",

    MAIN_CATEGORY: "bài viết chính",
    SEARCH_SUB: "Tìm kiếm bài viết",
    CATEGORY_DETAIL: "Chi tiết bài viết",
    NAME_UNSIGN: "Tên không dấu",
    UPDATED_AT: "Ngày cập nhật",
    UPDATED_BY: "Người cập nhật",
    CREATED_BY: "Người tạo",
    MAIN_CATEGORY_INFO: "Thông tin bài viết chính",
    SUBCATEGORIES: "Danh sách bài viết",
    ADD_POST: "Thêm bài viết",
    UPDATE_POST: "Cập nhật bài viết",
  },
  BUTTON: {
    ADD_POST: "Thêm bài viết",
    UPDATE_POST: "Cập nhật bài viết",
    SAVE: "Lưu",
    CANCEL: "Hủy",
  },
};
