name: Next.js Docker CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ducdang03/moneyez-web:latest

  deploy:
    runs-on: self-hosted
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Clean up old Docker resources
        run: |
          docker stop moneyez-web || true
          docker rm moneyez-web || true
    
      - name: Deploy to VPS
        run: |
          docker pull ducdang03/moneyez-web:latest
          docker run -d --name moneyez-web -p 3000:3000 ducdang03/moneyez-web:latest
  
      - name: Verify running containers
        run: docker ps -a
